[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#0B0A14"
secondaryBackgroundColor = "#1C1942"
textColor = "#F3F1FA"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false
